apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qpt7u816j-go
  janus-idp.io/tekton: qpt7u816j-go
  backstage.io/kubernetes-id: qpt7u816j-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qpt7u816j-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
